### PR TITLE
Support actor tokens

### PR DESCRIPTION
**Pull request by krallin**
Note: this isn't fully ready yet. I might need to add tests, and there's of course the `TO REMOVE` commit to remove.

---

This adds support for the token exchange OAuth flow. Not much to see here, most of the changes are in OAuth2.

cc @fancyremarker

### CODE REVIEW

**Comment by fancyremarker** [comment]
Released oauth2-aptible 0.9.5 w/ dependent changes. Merge this at will; not sure if you want to require `'>= 0.9.5'` for oauth2-aptible.

**Comment by krallin** [comment]
Yes, I was waiting for this release. Updated to require the new version. 

I'll wait for CI to complete before releasing (note: I updated `.travis.yml` to run on container infrastructure for faster builds). 

--

As a side note, we should try to all agree on what the versioning policy is (I think right now we don't).

**Comment by fancyremarker** [comment]
> As a side note, we should try to all agree on what the versioning policy is (I think right now we don't).

I agree with you that we should codify a versioning policy. Was there a specific question here?

**Comment by krallin** [comment]
@fancyremarker no, no question — I went ahead with what you asked last time (i.e. bumped the patch version), but I just noticed we'd also been bumping minor

**Pull request merged**
